version: '3'
services:
  postgres:
    image: postgres:14
    container_name:  postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: r8108074184R
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
  

volumes:
  postgres_data: